services:
  - type: web
    name: llm-api
    env: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8080"
    envVars:
      - key: MODEL_NAME
        value: "mistralai/Mistral-7B-Instruct-v0.1"
